
global:
  scrape_interval: 2s
  evaluation_interval: 2s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          
rule_files:

scrape_configs:
  - job_name: "consigne_api"
    static_configs:
      - targets: ["localhost:5248","localhost:5249"]
    metrics_path: /metrics-text